### ISSUE TITLE
SNAP LED GPIO mismatch

### ISSUE THREAD

**Issue by vtonder** [jack-h/mlib_devel#7]
The LED GPIO yellow block indices doesn't map to the LED lights correctly. i.e LED GPIO index 0 made the 3rd LED flicker on the SNAP board.

**Comment by jack-h** [comment]
Do you know the complete mapping -- e.g., are they all reversed?

**Comment by vtonder** [comment]
Hi Jack,

I don't have the mapping yet - I can figure that out. I was planning on 
working on SNAP board designs tomorrow so then I'll do that first thing 
in the morning.

Thanks,
Vereese

**Comment by vtonder** [comment]
Hi Jack, 

I have the mappings now. I thought it would be easier to just label the mappings on a picture of the SNAP board. snap1.png is a zoomed view of snap0.jpeg. Please let me know if anything is unclear. 

Thanks,
Vereese 

![snap0](https://cloud.githubusercontent.com/assets/11821568/14565355/c8436d08-02f8-11e6-9298-80bcf2bb8da0.jpeg)
![snap1](https://cloud.githubusercontent.com/assets/11821568/14565357/cb0505d8-02f8-11e6-855f-f17bc3f6eecc.png)
